name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the GitHub Actions runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Eclipse Temurin (AdoptOpenJDK)

      # Step 3: Build the application using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests  # Build the JAR (skip tests if needed)

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app-12 .

      # Step 5: Verify Docker image creation
      - name: List Docker images
        run: docker images

      # Optional: Step 6 - Push Docker image to Docker Hub or another registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-spring-boot-app-12 ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app-12:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app-12:latest
