name: Java CI with Maven

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Use JDK 17 (adjust based on your needs)
        distribution: 'adoptopenjdk'  # Use the AdoptOpenJDK distribution

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests  # Build the project and skip tests in this step

    # Step 4: Run tests
    - name: Run tests
      run: mvn test  # Run unit tests with Maven
